install: composer install
language: php
php:
- 7.0
- 7.1
- 7.2
script:
- vendor/bin/phpcs --standard=PSR1,PSR2 Soneritics/Buckaroo/
- mkdir -p build/logs
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests/
after_script:
  - php vendor/bin/coveralls -v
